.section .rodata

.globl MEM_END
MEM_END: .word mem_end

/*
.globl MEMORY_END
MEMORY_END: .word memory_end

.globl HEAP_START 
HEAP_START: .word heap_start

.globl HEAP_SIZE
HEAP_SIZE: .word heap_size

.globl TEXT_START 
TEXT_START: .word text_start

.globl TEXT_END
TEXT_END: .word text_end

.globl TEXT_SIZE
TEXT_SIZE: .word text_size

.globl RODATA_START
RODATA_START: .word rodata_start

.globl RODATA_END
RODATA_END: .word rodata_end

.globl RODATA_SIZE
RODATA_SIZE: .word rodata_size

.globl DATA_START
DATA_START: .word data_start

.globl DATA_END
DATA_END: .word data_end

.globl DATA_SIZE
DATA_SIZE: .word data_size

.globl BSS_START
BSS_START: .word bss_start

.globl BSS_END
BSS_END: .word bss_end

.globl BSS_SIZE
BSS_SIZE: .word bss_size

.globl KERNEL_STACK_START
KERNEL_STACK_START: .word stack_top

.globl KERNEL_STACK_END
KERNEL_STACK_END: .word stack_end

.globl KERNEL_STACK_SIZE
KERNEL_STACK_SIZE: .word kernel_stack_size
*/
